# Generated by Django 2.2 on 2020-04-05 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donor',
            old_name='name',
            new_name='full_name',
        ),
        migrations.RenameField(
            model_name='donor',
            old_name='location',
            new_name='location1',
        ),
        migrations.AddField(
            model_name='donor',
            name='location2',
            field=models.CharField(default='Kathmandu', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='donor',
            name='last_donated',
            field=models.DateField(),
        ),
    ]
