# Generated by Django 2.2 on 2020-04-05 10:02

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_auto_20200405_0945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor',
            name='email',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='number',
        ),
        migrations.AddField(
            model_name='donor',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='donor',
            name='phone_number',
            field=models.PositiveIntegerField(default=985, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donor',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='donor',
            name='age',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(17), django.core.validators.MaxValueValidator(70)]),
        ),
    ]
