# Generated by Django 2.2 on 2020-04-05 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200405_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='last_donated',
            field=models.DateField(blank=True, null=True),
        ),
    ]
