# Generated by Django 2.2 on 2020-04-06 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_donor_is_18'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='can_donate',
            field=models.BooleanField(default=True),
        ),
    ]
