# Generated by Django 2.2 on 2020-04-11 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_donorrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonorAccept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test', models.CharField(max_length=2)),
                ('bloodrequest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.BloodRequest')),
            ],
        ),
    ]
