# Generated by Django 2.2 on 2020-04-11 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_donoraccept'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DonorAccept',
        ),
    ]
